import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 30,
    justifyContent: 'space-between',
  },
  headerIconContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  icon: {
    textShadowColor: '#888',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#6C63FF',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 18,
    textAlign: 'center',
    color: '#666',
    marginBottom: 30,
  },
  card: {
    backgroundColor: '#F9F9F9',
    borderRadius: 15,
    padding: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  label: {
    fontSize: 20,
    color: '#444',
    textAlign: 'center',
    marginBottom: 20,
  },
  lengthSelector: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  roundButton: {
    backgroundColor: '#6C63FF',
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    marginHorizontal: 10,
    elevation: 3,
  },
  lengthDisplay: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingHorizontal: 30,
    paddingVertical: 15,
    elevation: 2,
  },
  lengthText: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
  generateButton: {
    backgroundColor: '#6C63FF',
    borderRadius: 10,
    paddingVertical: 20,
    alignItems: 'center',
    marginVertical: 20,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  resultContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  password: {
    fontSize: 22,
    color: '#333',
    backgroundColor: '#EEE',
    padding: 15,
    borderRadius: 10,
    textAlign: 'center',
    width: '90%',
    elevation: 2,
  },
  input: {
    height: 50,
    width: '90%',
    borderColor: '#6C63FF', // Bordas com maior contraste
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 15,
    backgroundColor: '#FFF',
    marginTop: 20,
    fontSize: 18,
    elevation: 2,
    color: '#333333', // Texto mais escuro para maior contraste
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  actionButton: {
    flex: 1,
    backgroundColor: '#6C63FF',
    padding: 15,
    borderRadius: 10,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  smallActionButton: {
    flex: 1,
    backgroundColor: '#6C63FF',
    paddingVertical: 10,
    borderRadius: 8,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  actionButtonText: {
    color: '#FFF',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 5,
  },
  shareAppButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#6C63FF',
    padding: 10,
    height: 48,
    borderRadius: 8,
    marginTop: 10,
    alignSelf: 'center',
    width: '100%',
  },
  shareAppButtonText: {
    color: '#FFF',
    fontSize: 14,
    marginLeft: 8,
    fontWeight: 'bold',
  },
});
